# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=200)),
                ('downloaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnet_id', models.CharField(max_length=42)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('quarter', models.CharField(max_length=42)),
                ('year', models.IntegerField(default=2016)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_forms.Session'),
        ),
    ]
