# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0004_auto_20160215_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
    ]
