# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0013_auto_20160226_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cnet_id',
            field=models.CharField(default='jmcclellan', max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
