# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0020_file_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='quarter',
        ),
        migrations.AddField(
            model_name='session',
            name='people_only',
            field=models.BooleanField(default=False),
        ),
    ]
