# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 15, 1, 53, 48, 443143, tzinfo=utc), verbose_name='date published'),
        ),
    ]
