# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0012_auto_20160224_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.TextField()),
                ('body', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cnet_id',
        ),
        migrations.AddField(
            model_name='assistant',
            name='email',
            field=models.CharField(default='negrodamus@uchicago.edu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistant',
            name='program',
            field=models.CharField(default='Happiness', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.CharField(default='CSGO', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='quarter',
            field=models.CharField(default='Endless Summer', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1984),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.CharField(default='negrodamus@uchicago.edu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='negrodamus@uchicago.edu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(default='Happiness', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_forms.Student'),
        ),
    ]
