# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0014_auto_20160229_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='duplicates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='duplicates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='duplicates',
            field=models.BooleanField(default=False),
        ),
    ]
