# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0015_auto_20160304_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='Course',
            new_name='courses_taught',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='Course',
            new_name='courses_taught',
        ),
    ]
