# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0016_auto_20160305_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_forms.Course'),
        ),
    ]
