# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0017_auto_20160305_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='subheading',
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
