# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0023_remove_course_downloaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='courses_taught',
            new_name='courses_in',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='courses_taught',
            new_name='courses_in',
        ),
    ]
