# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0031_remove_file_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='repeat_user',
        ),
    ]
